name: Build & Publish Docker Image
on:
  push:
    branches:
      - main

env:
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: extractions/setup-just@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/rauthy

          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     limit-access-to-users: zicklag

      - run: |
          export TERM=xterm
          export DEV_MODE=false
          cd frontend/
          npm install
          cd ../
          cargo install sqlx-cli --no-default-features --features rustls,sqlite,postgres
          docker network create rauthy-dev
          # docker run -e POSTGRES_USER=rauthy -e POSTGRES_PASSWORD=123SuperSafe --name rauthy-db-postgres --network rauthy-dev -d postgres:latest
          export DATABASE_URL=postgresql://rauthy:123SuperSafe@localhost:5432/rauthy
          just postgres-start
          just build ghcr.io/zicklag/rauthy
          docker push ghcr.io/zicklag/rauthy:latest


      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     limit-access-to-users: zicklag

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     file: Dockerfile
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
